global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'nestjs-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5000']
        labels:
          service: 'nestjs-api'
    metrics_path: '/mymetrics'
